### ISSUE TITLE
Concepticon mapping

### ISSUE THREAD

**Issue by xrotwang** [lexibank/polyglottaafricana#1]
The raw, unmapped concepts in this dataset are now available here https://github.com/lexibank/polyglottaafricana/blob/master/cldf/parameters.csv

Can any of the more experienced concepticon people help mapping it?

**Comment by chrzyki** [comment]
I'll get the mapping ready today.

**Comment by Kristina-Pianykh** [comment]
@chrzyki you know you can outsource it to me or let me know if you need any help.
