### ISSUE TITLE
Orthography profile?

### ISSUE THREAD

**Issue by xrotwang** [lexibank/polyglottaafricana#3]
@LinguList do you have a hunch how feasible orthography profiles for this dataset could be? Are there IPA transcriptions in reflex?

**Comment by tresoldi** [comment]
Seems a bit harder than simpler datasets, but not at TNG levels. Let me know if I should go forward.

**Comment by SimonGreenhill** [comment]
is it likely to be worth the effort?

**Comment by tresoldi** [comment]
I would need some time investigating if diacritics are what I expected (and they should, as it seems consistent with Africanist tradition), but I am learning to stop underestimating the effort.

Still, it would be very interesting to have this in terms of coverage. I can certainly be done in normal times if the focus is more on the sound classes, but finer phonetic details might take a while.

I suggest to leave this open.

**Comment by LinguList** [comment]
Can't tell by now, the source is from 1800+

**Comment by SimonGreenhill** [comment]
ok, this sounds like a lot of effort then. I'll close for now. @tresoldi if you get enthusiastic then go for it, but I suspect it's something that's in the too-hard basket.

**Comment by tresoldi** [comment]
Ok, I gave it a try, expected to finish in about two hours and of course it took more than twice the time. I'm opening a PR, discussing the profile there.

**Comment by SimonGreenhill** [comment]
Awesome :)

**Comment by LinguList** [comment]
@tresoldi, now that you helped so much here, can I give you more
responsibility? could you coordinate the PR for concepticon for the
concept list? As the concepts are in English, I think it can be done by
our fellow concepticon people. The tricky thing is: we need to columns,
one for reflex (which we use for lexibank) and one for the original. It
is on our google drive, @Kristina-Pianykh was working on it, as far as I
know.

**Comment by Kristina-Pianykh** [comment]
I still have a typed off csv sheet with the columns for Reflex (1) and original (2) glosses if it's still relevant. I just uploaded it to the [google drive](https://docs.google.com/spreadsheets/d/10VrKzLbB65kSm7JYT4S7uJLqNR1jJZ6sESGECApMECg/edit#gid=846503118). It's called Reflex_Original Polyglotta with all the entries from the book.
